version: '2'

services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d
    ports:
       - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

