version: '2'

services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  books_server:
    image: books_server:latest
    ports:
      - 3333:3333
    environment:
      - RECONNECT=6
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_DB_NAME=postgres
      - SERVER_PORT=3333
    depends_on:
      - postgres
